import type { Metadata } from "next";
import "./globals.css";
import { Inter, Oswald } from "next/font/google";
import Navbar from "./Component/Navbar";
import FitLogProvider from "./Context/FitLogProvider";
import { ToastContainer } from "react-toastify";
import Footer from "./Component/Footer";


const inter = Inter({
  variable: "--font-inter-custom",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald-custom",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
     
 className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
     <FitLogProvider>
      <ToastContainer />
        <Navbar/>
          <div>
               {children}
          </div>
          <Footer/>
</FitLogProvider>

        </body>
    </html>
  );
}
